### ISSUE TITLE
Enmap.find(func) errors while it shouldnt

### ISSUE THREAD

**Issue by DEVTomatoCake** [eslachance/enmap#109]
A week ago changes were made to Enmap.find(), which enforces a string as second argument - but according to typings/docs, when supplying a function as first parameter, the second parameter is optional:
https://github.com/eslachance/enmap/blob/45df42d87ef982b49ef33cc70f62e7dd20e2e2de/src/index.js#L1339

It seems like this exception wasn't implemented .-.
https://github.com/eslachance/enmap/blob/45df42d87ef982b49ef33cc70f62e7dd20e2e2de/src/index.js#L1352-L1353

Docs still have a function as example without using a second parameter. Workaround would be to supply a non-nil string as second parameter.

**Comment by eslachance** [comment]
You are absolutely correct, that should have been covered in the tests, I will fix it asap.

**Comment by eslachance** [comment]
@DEVTomatoCake 5.9.5 reverts last week's PR and will return usage to normal.
