### ISSUE TITLE
Is there a limit on enmaps?

### ISSUE THREAD

**Issue by ViolentCrumble** [eslachance/enmap#12]
I have an issue where any new Enmaps i add just do not persist.

I have about 12 or 13 that work no problem.

They all follow this format.
client.settings = new Enmap({ provider: new EnmapLevel({ name: 'settings' }) });

however I have tried adding a few new ones, up to 16 now and the last 3 just do not persist.

I have tried awaiting the set(), I have tried closing them after saving, and now I am at a loss.

I use the exact same method to retrieve and save for all of them and the first 13 work no problem, So i am sure my code is right.

Any more I add just do not save. My only reasoning is that maybe i have hit some internal limit on the amount of enmaps i am allowed to have in one project due to a memory limit or something?

I did try to use multi but i just get multi does not exist.

Any help would be appreciated.
Thanks.

**Comment by eslachance** [comment]
Had a discussion on this on Discord. There is no limit to the amount of enmaps that can be active theoretically. OS file handle limitations, HDD limitations and RAM limitations are pretty much the only known limits.
