### ISSUE TITLE
issue with enmap-mongo

### ISSUE THREAD

**Issue by KingCosmic** [eslachance/enmap#15]
Hey, was working on a discord bot and saw that i was way out of date on enmap (being at 2.0.4 and the latest being 4.0.12) I updated called it a night and went to sleep. but it wasnt fetching and data from my mongo db and was very confused, downgrading back to 2.0.4 fixed it and was wondering if there was any internal changes that may have screwed with enmap-mongo?

**Comment by eslachance** [comment]
Enmap version 4 no longer uses providers. If you want to cintue using providers you will need version 3.1.4, installed through `npm i eslachance/enmap#v3`. 

Enmap 4 *only* uses SQLite. See https://enmap.evie.codes/blog-posts/reason for more information.
