### ISSUE TITLE
Enmap per-server settings for Discord not saving

### ISSUE THREAD

**Issue by High-Fox** [eslachance/enmap#16]
I followed the guide on how to create per-server configs with enmap, and I can successfully edit, view and reset the keys and their respective values for each server, however when I restart my bot, all the changed revert and the values return to their original value. How can I fix this?

**Comment by eslachance** [comment]
Make sure you configured the enmap correctly. The very basics is: `client.settings = new Enmap({ name: "settings"});`. If the enmap does not have a name, it will not be persistent.

**Comment by High-Fox** [comment]
Does enmap store the persistent cache locally, or is it on a server somewhere?

**Comment by High-Fox** [comment]
I also do have the name setup, but the settings dont stay in memory.

**Comment by eslachance** [comment]
The data is stored by default in the `./data/enmap.sqlite` file, which is a standard sqlite database. 

Make sure your enmap version is up to date: `npm ls enmap` should show 4.something. If it does not, do `npm i enmap@latest` in your project. Also, ensure that you have the depenedency (`npm i better-sqlite-pool`, though if you didn't you'd get an error). 

If you still have issues please join my Discord server, https://discord.gg/N7ZKH3P

**Comment by High-Fox** [comment]
I am using Heroku to deploy my bot, does that affect anything?

**Comment by eslachance** [comment]
Unfortunately, Heroku is not supported by Enmap, and I have no intention of insuring this sort of support.
