### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by tommy1235** [eslachance/enmap#32]
`
gyp ERR! stack Error: Command failed: C:\Users\Tom W\AppData\Local\Programs\Pyth on\Python36\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];   gyp ERR! stack   File "", line 1                                         gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];          gyp ERR! stack                                ^                                  gyp ERR! stack SyntaxError: invalid syntax                                       gyp ERR! stack                                                                   gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)         gyp ERR! stack     at ChildProcess.emit (events.js:182:13)                       gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)              gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces s.js:251:5)
`

**Comment by eslachance** [comment]
node-gyp does not support python 3. Remove python 3, and follow these instructions precisely: 
https://enmap.evie.dev/install#pre-requisites

This installs the visual c++ build tools as well as python 2.7.15.

**Comment by eslachance** [comment]
If you need to keep python 3, run this command and try the install again: `npm config set python python2.7`
