### ISSUE TITLE
Error on this line.

### ISSUE THREAD

**Issue by Jaxii** [eslachance/enmap#37]
https://github.com/eslachance/enmap/blob/91e48895d8ab814260dd75d4921d1b96202d3ada/src/index.js#L857

Somehow fixed by changing it to const enmap = new Enmap({ name, options });
¯\_(ツ)_/¯

**Comment by MTGPROD** [comment]
Yes, but i think that is a example.

**Comment by eslachance** [comment]
That is not a mistake, at all. It's destructuring options given to the enmap into the object. If you are having any issue, please join the discord server for more help: https://discord.gg/N7ZKH3P
