### ISSUE TITLE
How to set ?

### ISSUE THREAD

**Issue by Shadowv7** [eslachance/enmap#42]
How to set "true" guildMemberBoost.enabled ?
![please](https://user-images.githubusercontent.com/60565794/75092808-cf91d200-557b-11ea-8b52-77e4c4bee393.JPG)

**Comment by eslachance** [comment]
Take a look at [the *path* property for the set() method](https://github.com/eslachance/enmap-docs/blob/4/api.md#enmapsetkey-val-path--enmap). If you need any further help, [please join Discord for support](https://discord.gg/4NE4bk7).
