### ISSUE TITLE
Discord.js v12 now requires Node v12

### ISSUE THREAD

**Issue by galnir** [eslachance/enmap#43]
![Screenshot_2](https://user-images.githubusercontent.com/36937694/75633718-146ad800-5c10-11ea-9b76-4a53ecf05c42.jpg)

I guess that's a problem since Enmap's installation page clearly mentions it can only be used with Node v10 :/

**Comment by eslachance** [comment]
Not that I'm tied to discord.js in any technical way in the first place (bots aren't the only thing using enmap). However, better-sqlite3 _can_ actually work in nodejs 12 and 13, I've tested. I should probably update that warnign.
