### ISSUE TITLE
"key was type of "object"" error when using enmap.push()

### ISSUE THREAD

**Issue by kekn9ne** [eslachance/enmap#46]
As the title says.
My enmap structure:
`
694554379243618315: {
    713536199536541757: {}
}
`

The code:
`bot.emojiMessages.push(message.guild.id, {"foo": "bar"}, "713536199536541757")`

If there is another way to add item to object please let me know.

**Comment by eslachance** [comment]
`push` is for arrays, not objects. `[]` is an array, `{}` is an object. If you want to add a property to an object, you can simply use set() with a path. See https://enmap.evie.dev/usage/objects to work with objects.
