### ISSUE TITLE
enmap.remove() erroring

### ISSUE THREAD

**Issue by JarnoPwr** [eslachance/enmap#47]
When I try to use enmap.remove() I just get this error.

```
5|Mythonia-Bot  | TypeError: index.indexOf is not a function
5|Mythonia-Bot  |     at Map.remove (/home/minecraft/servers/Mythonia-Bot-V4/node_modules/enmap/src/index.js:721:34)
5|Mythonia-Bot  |     at Object.run (/home/minecraft/servers/Mythonia-Bot-V4/commands/blacklist.js:44:26)
5|Mythonia-Bot  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by eslachance** [comment]
I'll need a lot more information than just the function you're using. What is the value stored in the enmap for the key, and what arguments are you providing to remove(), specifically? I need to be able to reproduce this in order to find a solution.
