### ISSUE TITLE
enamp.remove() with object array support when?

### ISSUE THREAD

**Issue by Zendrex** [eslachance/enmap#49]
Trying to do some refactoring, realized its unsupported. Any planned support for this down the line?

ex: `someEnamp.remove(key, (k) => k.id == "someID", "someArray");`

**Comment by Zendrex** [comment]
I'm aware I can use the sweep function, however a simpler method like above would be appreciated.

This seems excessive...
ex: `someEmap.sweep((k => k.id == "someID" && k.objArray.find((o) => o.key == "someValue")))`

**Comment by eslachance** [comment]
Not a bad way to do this! I'll implement function support as soon as I get the chance 😊

**Comment by eslachance** [comment]
Resolved by b70fc4b9936755ca37e20e98ae401a1285f27bda , version 5.4.0
