### ISSUE TITLE
incorrect get types

### ISSUE THREAD

**Issue by thetayloredman** [eslachance/enmap#54]
when `Enmap#get()` is invoked with a `path` it returns `V[path]`, not `V`...

**Comment by WilsontheWolf** [comment]
What do you mean by this?

**Comment by eslachance** [comment]
Would typescript even recognize `V[path]` considering `V` is "a value" and there's no defined structure for it? Does it even matter? It's basically an `any` type, so I don't see how that would make much of a difference.

**Comment by thetayloredman** [comment]
> What do you mean by this?

For example, (enmap type `Enmap<string, { hello: string }>`)

```ts
myEnmap.set('key', { hello: 'world' });
myEnmap.get('key', 'hello'); // => 'world' but typed T ({ hello: string })
```

> Would typescript even recognize `V[path]` considering `V` is "a value" and there's no defined structure for it? Does it even matter? It's basically an `any` type, so I don't see how that would make much of a difference.

`V`'s type can be specified as I do: `public commands: Enmap<string, Command>`

It *may* be possible using a type param:

```ts
public get(key: string): V;
public get<P extends keyof V>(key: string, path: P): V[P]; // or something
```

**Comment by thetayloredman** [comment]
Here's a small example of my problem in context:

```ts
// src/lib/client.ts
import Command from '@lib/interfaces/Command';

// ...

export default class Client extends BaseClient {
    // ...

    public commands: Enmap<string, Command>
}

// src/lib/interfaces/Command.ts

import CommandConfig from '@lib/interfaces/CommandConfig'

export default interface Command {
    // ...
    config: CommandConfig;
}

// src/lib/interfaces/CommandConfig.ts

export default interface CommandConfig {
    name: string;
    // ...
}

// src/index.ts

// ... init and command handling

const config = client.commands.get(command, 'config'); // should return CommandConfig not Command
//    ^^^^^^ type Command

console.log(config.name)
// error as Command.name isn't a thing
```

**Comment by eslachance** [comment]
Well, you know how to open a PR, right? ;)

**Comment by thetayloredman** [comment]
Let me find my convo in the TS official discord...

**Comment by thetayloredman** [comment]
Message link: https://discord.com/channels/508357248330760243/766001660375859262/793546090993156104
(server: https://discord.gg/YDxEgqTX)

[BadBoyHaloCat] 12/29/2020
Can anyone help me fix types on https://github.com/eslachance/Enmap ?
The problem is `get()`
It takes `(key: string, path?: string)` and returns `V`
but `path` would return `V[path]`
would this work?
```
```ts
public get(key: string): V | undefined;
public get<P extends string>(key: string, path: P): V[P] | undefined
```
?

---

[mkantor] 12/29/20
`V[P]` probably isn't what you want, the type of `V` would have to be constrained to be like `extends Record<string, ?>` or something (so can be indexed by any `string`)
what does a "path" mean in this context? like indexing into nested maps?
this is probably closer:
```ts
public get(key: string): V | undefined;
public get<P extends keyof V>(key: string, path: P): V[P] | undefined
```
but looking at https://github.com/eslachance/enmap/blob/master/typings/index.d.ts#L137-L138 i see that the path can also be a dot-notated thing for deep indexing (`"foo.bar"`). that won't work with this type; you'd need some fancy template literal type stuff methinks

---

[GitHub Lines] [✔️ BOT] 12/29/2020
```ts
* @param path The path to the property to modify inside the value object or array.
* Can be a path with dot notation, such as "prop1.subprop2.subprop3"
```

---

/--- @mkantor what does a "path" mean in this context? like indexing into nested maps?
[BadBoyHaloCat] 12/29/2020
objects
so like
```ts
Enmap [Map] {
  'key' => { someNestedObj: { hello: 'world' } }
}
```
```ts
myEnmap.get('key', 'someNestedObj'); // => Object { hello: 'world' }
myEnmap.get('key', 'someNestedObj.hello'); // => 'world'
```

---

*help channel closed*

**Comment by RealShadowNova** [comment]
> > What do you mean by this?
> 
> For example, (enmap type `Enmap<string, { hello: string }>`)
> 
> ```ts
> myEnmap.set('key', { hello: 'world' });
> myEnmap.get('key', 'hello'); // => 'world' but typed T ({ hello: string })
> ```
> 
> > Would typescript even recognize `V[path]` considering `V` is "a value" and there's no defined structure for it? Does it even matter? It's basically an `any` type, so I don't see how that would make much of a difference.
> 
> `V`'s type can be specified as I do: `public commands: Enmap<string, Command>`
> 
> It *may* be possible using a type param:
> 
> ```ts
> public get(key: string): V;
> public get<P extends keyof V>(key: string, path: P): V[P]; // or something
> ```

What about when the path uses for notation? Allowing for such will only index shallow-like. Also, what about those who are not storing objects? We are now able to store many different types now. So this would be only useful if everyone is storing objects.

**Comment by RealShadowNova** [comment]
> ```ts
> const config = client.commands.get(command, 'config');
> ```
I also want to point out, if you really want the proper type, why can't you just index yourself instead of making it complicated for a package that isn't primarily directed for TS users anyways?

e.g.
```ts
const config = client.commands.get(command)?.config // CommandConfig
```

**Comment by RealShadowNova** [comment]
> ```ts
> export default class Client extends BaseClient {
>     // ...
> 
>     public commands: Enmap<string, Command>
> }```

Also, why are you saving commands in a database? There isn't any reason to be saving commands to a database (unless this enmap is for memory only), unless absolutely it's necessary for whatever odd reason. Commands are generally and should be saved in memory using a Map, or if you even want some more advanced functions use a Collection from `@discordjs/collection`.

**Comment by thetayloredman** [comment]
> > ```ts
> > const config = client.commands.get(command, 'config');
> > ```
> 
> I also want to point out, if you really want the proper type, why can't you just index yourself instead of making it complicated for a package that isn't primarily directed for TS users anyways?
> 
> e.g.
> 
> ```ts
> const config = client.commands.get(command)?.config // CommandConfig
> ```

True...

---

> > ```ts
> > export default class Client extends BaseClient {
> >     // ...
> > 
> >     public commands: Enmap<string, Command>
> > }
> > ```
> 
> Also, why are you saving commands in a database? There isn't any reason to be saving commands to a database (unless this enmap is for memory only), unless it's absolutely necessary for whatever odd reason. Commands are generally and should be saved in memory using a Map, or if you even want some more advanced functions use a Collection from `@discordjs/collection`.

It is memory-only, and I just prefer Enmap for whatever reason.

**Comment by RealShadowNova** [comment]
I'm going to leave this issue as resolved @eslachance if you could please close this issue.
