### ISSUE TITLE
Enmap with typescript

### ISSUE THREAD

**Issue by CrownlessX** [eslachance/enmap#62]
Hi

I started with refactoring of my discord bot from js to typescript. 
How can i use enmap with it? 
It tells that value are not exists and doesn't allow me to use it as before

**Comment by dan-online** [comment]
Hi @CrownlessX, enmap has typings in [index.d.ts](https://github.com/eslachance/enmap/blob/master/typings/index.d.ts) and so it should work, it would help if you could share the error

**Comment by CrownlessX** [comment]
Thank you quick response! 

@dan-online 

I'm using it with js as:
client.guildsSettings = new Enmap({
    name: "guildsSettings",
    fetchAll: false,
    autoFetch: true,
    cloneLevel: 'deep'
});


But for typescript(newb) got:
Property 'guildsSettings' does not exist on type 'Client'

**Comment by RealShadowNova** [comment]
> Hi @CrownlessX, enmap has typings in [index.d.ts](https://github.com/eslachance/enmap/blob/master/typings/index.d.ts) and so it should work, it would help if you could share the error

I'm pretty sure that the typings need a good updating/refactoring, but I have been too busy and lack the incentive to do so.

**Comment by CrownlessX** [comment]
Probably, I'm just too bad with understanding how it does work. 
I don't need to "stick" it to a client, i suppose, and use it as solo obj

**Comment by dan-online** [comment]
Actually @RealShadowNova the typings aren't the problem, because "client" is a Discord constructor it's not made to have "guildsSettings", I believe you have to add the type as being enmap

**Comment by RealShadowNova** [comment]
> Thank you quick response! 
> 
> @dan-online 
> 
> I'm using it with js as:
> client.guildsSettings = new Enmap({
>     name: "guildsSettings",
>     fetchAll: false,
>     autoFetch: true,
>     cloneLevel: 'deep'
> });
> 
> 
> But for typescript(newb) got:
> Property 'guildsSettings' does not exist on type 'Client'
> 

The solution to this is augmentation. You can read up on it [here](https://www.typescriptlang.org/docs/handbook/declaration-merging.html).

Until then, somewhere you can stick this: ```typescript
declare module "discord.js" {
  interface Client {
    guildSettings: Enmap
  }
}
```

**Comment by CrownlessX** [comment]
@RealShadowNova 
Great! 
Will try to! 
Thank you a lot!

**Comment by eslachance** [comment]
Closing as this seems to be resolved - if you still need assistance, please don't hesitate to reopen a ticket or join our Discord!

**Comment by thetayloredman** [comment]
> @RealShadowNova
> Great!
> Will try to!
> Thank you a lot!

The most efficient solution is to add `typings/Augments.d.ts` to your project with the above code, and making your own `class Client extends DJSClient`.

**Comment by RealShadowNova** [comment]
> > @RealShadowNova
> > Great!
> > Will try to!
> > Thank you a lot!
> 
> The most efficient solution is to add `typings/Augments.d.ts` to your project with the above code, and making your own `class Client extends DJSClient`.

I know, literally discussed in the Discord server.
