### ISSUE TITLE
Error at index.js:55

### ISSUE THREAD

**Issue by ItzRaiin94** [eslachance/enmap#8]
![2017-11-11 19_25_59-c__windows_system32_cmd exe](https://user-images.githubusercontent.com/31005993/32692772-2991709a-c716-11e7-8c75-37acad24a5bc.png)
The following error happens whenever I try to boot my bot using discord.js - It's using enmap for an RPG system.

**Comment by eslachance** [comment]
Sorry for the time to respond: I think maybe your version of node is too old. You need version 7.6 or higher to run this, and in 7.6 you need the --harmony flag (async is a relatively new thing in node)

**Comment by ItzRaiin94** [comment]
Ah sorry, my node version was 6.11.2, thanks for telling me the problem.
It's ok, we all have lives and can't always check everything.
