### ISSUE TITLE
Resolve TS issue that broke in later versions

### ISSUE THREAD

**Issue by eslachance** [eslachance/enmap#81]
Ref: https://discord.com/channels/298508738623438848/473491355520204800/864584545784168519

> aha! even with synthetic imports, it didn't work. i did a quick google search and looked at a repo that used enmap and typescript, downgraded my enmap version to the one that the repo was using (5.7.1) and it works now!

Since 5.7.1, one of the versions broke the TS usage. Mayhap someone could take a look, and fix it? ^_^

**Comment by andre-1337** [comment]
Just took a look at it, 5.8.6 seems to be the only one breaking when used with TS. I'm going to look at the source code between 5.8.5 and 5.8.6 to hopefully spot what caused this.
