### ISSUE TITLE
TS issue

### ISSUE THREAD

**Issue by aliam1712** [eslachance/enmap#88]
There is an issue in typescript when you specify the dataDir option it shows you an error that the directory doesn't exist

**Comment by RealShadowNova** [comment]
How's this related to TypeScript, can you show the error?

**Comment by thetayloredman** [comment]
> How's this related to TypeScript, can you show the error?

Because there's no reply, my most likely guess is they are using a dist/ dir as compilation destination and they need to change the process CWD to fix it

**Comment by eslachance** [comment]
Issue is old and never got any reply - closing as it's most likely no longer relevant.
