### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ShadowGaming100** [eslachance/enmap#97]
/home/runner/XGiveaway-Bot/node_modules/enmap/src/index.js:120
    this.#name = options.name ?? '::memory::';
                               ^

SyntaxError: Unexpected token '?'
Hint: hit control+c anytime to ent

**Comment by dan-online** [comment]
hey @ShadowGaming100 could you try using node v14

**Comment by ShadowGaming100** [comment]
> hey @ShadowGaming100 could you try using node v14
but i am using latest version
i fixed it

**Comment by KavithBro** [comment]
> 

i have the same issue....can u tell me how u fixed it

**Comment by eslachance** [comment]
> i have the same issue....can u tell me how u fixed it

By using node 14 or higher.
